Implemented K means from scratch.
Compare output to MATLAB or Python’s standard function(s), as well as contrast run times

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import numpy as np
import matplotlib.pyplot as plt
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as img

from scipy import misc
import cv2
  

In [3]:
import numpy as np
import time
from tqdm import tqdm
import matplotlib.pyplot as plt

In [4]:
image=cv2.imread('/content/drive/MyDrive/road.jpg',cv2.COLOR_BGR2GRAY)

In [5]:
image.shape

(2048, 2048)

# K-Means from Scratch

In [6]:
import numpy as np
import cv2
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow

def Kmeans_scratch(image,k,iters=3):
    img=image.copy()
    h,w=img.shape
    orig=image.copy()
    Klusters=np.random.randint(0,255,size=k)  # Initializing Clusters Centroids
    print('init clusters', Klusters)
    for it in range(iters):
        img=image.copy()
        for i in range(h):
            for j in range(w):
                pnt=img[i][j]
                diff=np.abs(Klusters-pnt) # The distance from Centroid to pixels
                c=np.argmin(diff)         # Closest Point is chosn as centroid and updated
                img[i][j]=Klusters[c]
    loss=0
    l=[]
    for i in range(k):
        Ys,Xs=np.where(img==Klusters[i])
        kth_points=orig[Ys,Xs]
        l.append(np.sum(Klusters[i]-kth_points))
        Klusters[i]=np.mean(kth_points)
    loss=np.sum(l)    
    print('Cluster centroids at iteration-{}'.format(it+1), Klusters)
    return Klusters

# K-Means Inbuit Function

In [7]:
from sklearn import cluster
def Kmeans_inbuit(image,k):
  km=cluster.KMeans(n_clusters=k)
  km.fit(image)
  ym=km.predict(image)
  print(ym)

  return ym

# Runtime Testing

**K-Means From Scratch**

In [8]:
runtime = []
#for n in tqdm(100):
sum=0
for a in range(10):  
  
  start = time.time()
  
  Kmeans_scratch(image,k=4)
      
  end = time.time()

  sum+=(end-start)

  if a == 9:
    runtime.append(sum/10)

init clusters [192  99  17 185]
Cluster centroids at iteration-3 [206  88  39 171]
init clusters [  4  89 136  98]
Cluster centroids at iteration-3 [ 34  65 184 103]
init clusters [ 14  95 213 159]
Cluster centroids at iteration-3 [ 38  82 204 163]
init clusters [ 86 149 169  76]
Cluster centroids at iteration-3 [ 96 138 196  47]
init clusters [ 51 163 114 130]
Cluster centroids at iteration-3 [ 48 192  99 134]
init clusters [237  32 153 116]
Cluster centroids at iteration-3 [209  45 173  97]
init clusters [116  26  24 179]
Cluster centroids at iteration-3 [ 99  46  19 193]
init clusters [245 170  17 223]
Cluster centroids at iteration-3 [239 149  51 208]
init clusters [235 191 181 223]
Cluster centroids at iteration-3 [237 196  77 214]
init clusters [ 55 162  57 236]
Cluster centroids at iteration-3 [ 39 166  79 213]


In [9]:
runtime

[82.34755582809449]

**K-Means Inbuilt Function**

In [10]:
runtime1 = []
#for n in tqdm(100):
sum=0
for a in range(10):  
  
  start = time.time()
  
  Kmeans_inbuit(image,k=4)
      
  end = time.time()

  sum+=(end-start)

  if a == 9:
    runtime1.append(sum/10)

[2 2 2 ... 1 1 1]
[1 1 1 ... 3 3 3]
[0 0 0 ... 1 1 1]
[0 0 0 ... 1 1 1]
[1 1 1 ... 3 3 3]
[1 1 1 ... 2 2 2]
[1 1 1 ... 0 0 0]
[1 1 1 ... 0 0 0]
[1 1 1 ... 0 0 0]
[0 0 0 ... 3 3 3]


In [11]:
runtime1

[2.439453363418579]

The runtime of the builtin funtion is considerably less than the function we implemented from scratch.

> 

The runtime of the implemented function is large because there are a lot of computation involved along with indexing and parsing finding the centroid of the clusters. 